### ISSUE TITLE
Define STAC metadata structure

### ISSUE THREAD

**Issue by hrodmn** [developmentseed/noaa-hrrr#1]
## Background
The NOAA HRRR data ([Planetary Computer catalog entry](https://planetarycomputer.microsoft.com/dataset/storage/noaa-hrrr), [NOAA product page](https://www.nco.ncep.noaa.gov/pmb/products/hrrr/#CO)) is a continuously updated forecast data product. The data are currently housed in Azure but are not yet cataloged. Development Seed is working on improving the accessibility of the data for analytical applications.

### Data structure
- There are two regions: CONUS and Alaska
- Every hour, new hourly forecasts are generated for many atmospheric attributes for each region
  - All hours (`00-23`) get an 18-hour forecast
  - Hours `00`, `06`, `12`, `18` get a 48-hour forecast
  - One of the products (`subh`) gets 15 minute forecasts (four per hour per attribute)
- The forecasts are broken up into 4 products,  
- An hourly forecast for all variables from a product is uploaded to Azure storage in the GRIB2 format
- Each GRIB2 file has hundreds to thousands of variables
- Each .grib2 file is accompanied by a .grib2.idx which has variable-level metadata including the starting byte for the data in that variable (useful for making range requests instead of reading the entire file) and some other descriptive metadata
  - the .grib2.idx files could save us from working with the full .grib2 file when generating the STAC metadata

## Goal
Generate STAC metadata that supports these use-cases:
1. Queries to get the hrefs for the GRIB files that match some set of conditions (reference time, forecast time, specific variable, etc)
    - Bonus points if these STAC items can be useful for producing the datacube metadata!
2. A single(?) STAC item that represents a data cube (VirtualiZarr/kerchunk) of the entire dataset that can be queried/analyzed directly with `xarray`
    - one item per region? 

## Relevant links
- Here are a few example collections that confront the same problem:
  - ECMWF Open Data collection ([PC catalog entry](https://planetarycomputer.microsoft.com/dataset/ecmwf-forecast), [stactools package](https://github.com/stactools-packages/ecmwf-forecast)) 
  - NOAA GEFS ([stactools package](https://github.com/stactools-packages/noaa-gefs))

- There is a great discussion about how to handle forecast data in a STAC collection here: https://github.com/radiantearth/stac-spec/discussions/1169

- There is a proposed `forecast` extension here: https://github.com/stac-extensions/forecast

- Here is a notebook with some details about the structure of the data and examples for using it: https://github.com/microsoft/AIforEarthDataSets/blob/main/data/noaa-hrrr.ipynb

## Proposed solution
- Follow the patterns from the ECMWF dataset because it will make the HRRR metadata consistent with similar forecast products in the Planetary Computer Catalog.
  - This approach is appealing because it does not require opening any GRIB2 files to generate the metadata (we will be needing to process a **lot** of these items) and because we might be able to use the kerchunk logic for our work on the big datacube asset.
- Follow the NOAA GEFS collection's use of the `forecast` extension instead of `hrrr:reference_time`
- use the forecast time (not model run time) to set the item `datetime` property
- make separate items for each variable and forecast hour
- TODO: spec out datacube `Item` metadata

Example STAC item metadata for a GRIB2 `Item`:
```json
...
    {
      "id": "noaa-hrrr-20240524-t00-prs-FH12",
      "bbox": [...],
      "type": "Feature",
      "links": [...],
      "assets": {
        "data": {
          "href": "https://noaahrrr.blob.core.windows.net/hrrr/hrrr.20240524/conus/hrrr.t00z.wrfprsf12.grib2",
          "type": "application/wmo-GRIB2",
          "roles": [
            "data"
          ],
          "raster:bands": [
            {"data_type": "float64", ...}, # more information about each band
          ]
        },
        "index": {
          "href": "https://noaahrrr.blob.core.windows.net/hrrr/hrrr.20240524/conus/hrrr.t00z.wrfprsf12.grib2.index",
          "type": "application/x-ndjson",
          "roles": [
            "index"
          ]
        }
      },
      "geometry": {...},
      "collection": "noaa-hrrr",
      "properties": {
        "datetime": "2024-05-24T12:00:00Z",
        "forecast:reference_datetime": "2024-05-24T00:00:00Z",
        "forecast:horizon": "PT12H",
        "hrrr:region": "conus",
        "hrrr:cc": "12",
        "hrrr:type": "prs"
      },
      "stac_extensions": [
        "https://stac-extensions.github.io/raster/v1.1.0/schema.json",
        "https://stac-extensions.github.io/projection/v1.0.0/schema.json",
        "https://stac-extensions.github.io/timestamps/v1.0.0/schema.json",
        "https://stac-extensions.github.io/forecast/v1.0.0/schema.json"
      ],
      "stac_version": "1.0.0"
    },
...
```

## Questions
- How should we handle multiple timestamps within a single GRIB2 asset for the `subh` variable?
  - i.e. a time dimension AND attribute dimension are represented in bands within a single file
  - can we do this with `raster:bands` e.g. https://github.com/stactools-packages/noaa-gefs/blob/main/src/stactools/noaa_gefs/stac.py#L335
- Do we need to open a connection to the GRIB2 file to get specific GRIB band-level metadata or can we assume that it is constant across all files for a given variable?
  - can we use the .grib2.index files to achieve this?
- Would the `kerchunk:indices` property be useful for our datacube work?
  - https://github.com/stactools-packages/ecmwf-forecast/blob/main/src/stactools/ecmwf_forecast/_kerchunk_helper_functions.py
  - https://github.com/stactools-packages/ecmwf-forecast/blob/main/src/stactools/ecmwf_forecast/stac.py#L412

cc @zacharyDez @abarciauskas-bgse @sharkinsspatial @vincentsarago @TomAugspurger

**Comment by TomAugspurger** [comment]
Thanks @hrodmn. A few quick suggestions that shouldn't be taken too seriously

> Each GRIB2 file has hundreds to thousands of bands

This was probably the thing I struggled with the most when working with ecmwf-forecast. If we take building data cubes as our end goal (which I think is reasonable), it's not always obvious what the relationship is between a list of grib files and one or more data cubes (xarray Datasets). [cfgrib](https://github.com/ecmwf/cfgrib) has some conventions for building a list of xarray Datasets out of a STAC item, which might be worth following. But in general, a single GRIB file might map to multiple Datasets, which makes things messy (not sure if it applies to the HRRR files).


> How should we handle multiple timestamps within a single GRIB2 asset for the subh variable?

Can you give a bit more detail on this? (But in general, my recommendation will probably be "do whatever cfgrib does")

> Do we need to open a connection to the GRIB2 file to get specific GRIB band-level metadata or can we assume that it is constant across all files for a given variable?

I'm generally OK with trusting the provider's documentation around how things are organized, but it would be good to have an easy way to validate that the STAC items are correct.

> Would the kerchunk:indices property be useful for our datacube work?

I'm not sure yet. I think there's a larger discussion to be had about where Kerchunk metadata lives (briefly, it might go in STAC metadata (and from the stac-geoparquet exports be available in parquet for bulk queries) or it might go in sidecar JSON / parquet files.) If possible, I would defer this initially, while we work out the best way to do that.

**Comment by hrodmn** [comment]
Thanks for your suggestions, @TomAugspurger!

> > Each GRIB2 file has hundreds to thousands of bands
> 
> This was probably the thing I struggled with the most when working with ecmwf-forecast. If we take building data cubes as our end goal (which I think is reasonable), it's not always obvious what the relationship is between a list of grib files and one or more data cubes (xarray Datasets). [cfgrib](https://github.com/ecmwf/cfgrib) has some conventions for building a list of xarray Datasets out of a STAC item, which might be worth following. But in general, a single GRIB file might map to multiple Datasets, which makes things messy (not sure if it applies to the HRRR files).

Thanks for the `cfgrib` suggestion, I'll take a look!
 
> > How should we handle multiple timestamps within a single GRIB2 asset for the subh variable?
> 
> Can you give a bit more detail on this? (But in general, my recommendation will probably be "do whatever cfgrib does")

The difference between `subh` and the rest of the variables is that, in addition to the data variable dimension, there is a time dimension represented in the bands within a single GRIB2 file (all other variables represent a single forecast time + reference time combination). `cfgrib` handles this by adding a `step` dimension to the `xarray.Dataset` with 15 minute intervals. I am not sure why it does that instead of using the existing `time` dimension, but I guess it would allow you to do analysis on a time series of e.g. step 3 (45 minute) forecasts. It does make it a little trickier to combine multiple `subh` files for analysis, i.e. concatenating the 15-minute interval forecasts across multiple hours.

> > Would the kerchunk:indices property be useful for our datacube work?

> I'm not sure yet. I think there's a larger discussion to be had about where Kerchunk metadata lives (briefly, it might go in STAC metadata (and from the stac-geoparquet exports be available in parquet for bulk queries) or it might go in sidecar JSON / parquet files.) If possible, I would defer this initially, while we work out the best way to do that.

Good call. For now I could just add the `datacube` extension to the individual STAC assets so that the bands within each GRIB are documented.

@abarciauskas-bgse  @sharkinsspatial After thinking about it some more, I think it might make sense to declare the separate `variables` as **assets** within a single item rather than creating separate **items** (or **collections**) for each `variable`. This seems intuitive to me since the groups of GRIB files (one for each `variable`) represent a single forecast hour + cycle run hour and we could explain a lot about the structure of the whole collection using the `item_assets` extension.

**Comment by hrodmn** [comment]
After hacking on the STAC metadata in #3 and after much discussion with @sharkinsspatial and @abarciauskas-bgse I have a few more thoughts and a few alternative approaches, each with a set of pros and cons.

Here are some more details about the HRRR data that make it challenging to produce useful STAC metadata:
- Within a single .grib file, all of the variables cannot be read into a single xarray dataset
  - not all variables share the same dimensions
  - all variables have x/y, some have atmospheric level (e.g. surface), some have height above ground, etc
- Within a single product (e.g. `sfc`), the number of variables present in a .grib file varies according to the forecast hour
  - this means that we cannot reasonably include collection-level datacube extension metadata since the list of variables among .grib files within a single product is not consistent
- Even if we do fill out the datacube metadata, we do not yet have a way to specify which exact coordinates in each dimension have data for any given variable such that the metadata can be used to constrain an interactive application to a valid list of combinations of variable, forecast_time, and level

## Option 1: many collections

sharkinspatial proposed this as an option that would be most efficient on the STAC side:
1. Create separate collections for each product x forecast hour group (either FH00-01 or FH2-48) combination
    - this is how NOAA breaks down the inventory of the data catalog: e.g. [FH00-01](https://www.nco.ncep.noaa.gov/pmb/products/hrrr/hrrr.t00z.wrfprsf00.grib2.shtml) [FH02-48](https://www.nco.ncep.noaa.gov/pmb/products/hrrr/hrrr.t00z.wrfprsf02.grib2.shtml)
2. For each collection, add collection-level datacube extension metadata

### Pros:
- Don't need to stuff datacube metadata all the way down in the items or assets, just store it once in the collection objects since all items within a collection have assets with the same structure
- Downstream applications (like dynamic tiling services) could use the datacube metadata to formlate queries to the raw data for visualization or analysis
- This is consistent with other large-scale STAC collections with similar between-item asset inconsistencies (e.g. HLS sentinel vs landsat)

### Cons:

- A .grib file does not completely fill out a datacube, i.e. not all combinations of all dimensions have data for a given variable
  - we would need some way to declare which combinations exist (this is not a part of the datacube spec yet)
- The separation of data into multiple collections can impose a barrier to users who want to explore the full dataset

## Option 2: one collection, all coherent datacubes listed as assets within items

1. One collection with one item per cycle run x forecast hour combination
2. Set up the list of `datacubes` that `cfgrib` (and `Herbie`) can read as assets within each STAC item.
  - This would mean tucking the datacube metadata along with some special properties into the asset metadata that could be passed to `cfgrib` or `Herbie` to selectively download/read the specified datacube from the full .grib files.
  - Many assets per .grib file

When you read a .grib file with `cfgrib.open_datasets`, it returns a list of ~dozens of datacubes. This is because some of the variables in the .grib file can be combined into coherent datacubes.

```python
!wget https://noaahrrr.blob.core.windows.net/hrrr/hrrr.20240530/conus/hrrr.t06z.wrfsfcf00.grib2 -O /tmp/hrrr.20240530__conus__hrrr.t06z.wrfsfcf00.grib2

import cfgrib

local_file = "/tmp/hrrr.20240530__conus__hrrr.t06z.wrfsfcf00.grib2"

cfgrib_datasets = cfgrib.open_datasets(
    local_file,
)
```

This returns a list of 47 xarray datasets with one or more data variables. Many have two dimensions (x and y), but some have a third dimension like `heightAboveGround`.

It would not be typical to store references to internal layers of a .grib file as assets, but it is a natural way to access the data.

Pros:
- Shortens the ramp for a user to send a query to a the STAC and load the results into xarray
- Can use the item-assets extension to make the full list of datacubes viewable at the collection-level
  - We still have the same issue as before with inconsistent variables between items, but could list all possible datacubes/assets in item-assets then limit the list to the available assets in each item.
- Variable discovery should be easier if each datacube has a reasonable description

Cons:
- This seems very specific to xarray as an application which is not something I have seen in a STAC collection
- There will be hundreds of assets in every item
- Storing all of the datacube metadata at the asset-level is relatively inefficient


If anyone has any strong reactions to these options I would love to hear them!

**Comment by sharkinsspatial** [comment]
@hrodmn in relation to 
> we would need some way to declare which combinations exist (this is not a part of the datacube spec yet)

I think a possible approach here might be adding another custom property to the [datacube variable's](https://github.com/stac-extensions/datacube?tab=readme-ov-file#variable-object) with the following structure

```
{
   "dimension_domains": {
       "level": [
           "entire atmosphere",
           "cloud_top",
           "surface"
      ]
   }
}
```
where each `dimension_domains` key must be a key in `cube:dimensions`.

I'll try to crack open some notebooks today to investigate but it also appears that when [applying specific level filters with Herbie](https://herbie.readthedocs.io/en/stable/user_guide/tutorial/inventory.html) that it seems to coerce the `level` coordinate name to one that is specific to the selected value (`isobaricInhPa` in this case).  Have you noticed this behavior?

**Comment by hrodmn** [comment]
Another possible approach would be to treat the individual "bands" in the GRIB files as assets within the items. We could keep the base `.grib` and `.grib.idx` assets and add assets that represent the byte range either as asset-level properties or directly in the `href` using [`/vsisubfile`](https://gdal.org/user/virtual_file_systems.html#vsisubfile-portions-of-files), e.g. `/vsisubfile/57675323_1224134,/vsicurl/https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrrr.20210103/conus/hrrr.t12z.wrfsfcf06.grib2`.

It would not require a very complicated application to concatenate the same assets from different items along a time dimension in xarray and it could be used without installing `eccodes` or `cfgrib`.

Here is a gist showing how you can load tiny subsets of data into xarray without any downloading logic using `/vsisubfile` and `/vsicurl`: https://gist.github.com/hrodmn/278e50aa94ef4748cdc8e51d4db3b354/8e480f513930c807ef599b506f889e1536a9166f

To make it easier to combine assets from a single item into a datacube, we could add an asset-level property that indicates which group or datacube each asset can be added to, but maybe this would just be a separate `datacube` asset within each item.

**Comment by TomAugspurger** [comment]
> Another possible approach would be to treat the individual "bands" in the GRIB files as assets within the items. 

FWIW, over time I've become more of a "purist" that assets in STAC items should refer to actual assets, and that things like this example extracting a variable from a file are better off in an extension on the item or asset. For example, as an extension on the assets:

```
"assets": {
"data": {
    "href": "...",
    "variables": {
        "DPT": {
           "offset": "...",
           "length": "...",
    }
}
}
```

That leaves the assets as plain links to files, and a (not very complicated, as you say) client application could pick out the extra metadata if they want to construct the efficient range queries.

**Comment by hrodmn** [comment]
@TomAugspurger thanks for the suggestion. I tried the slices as assets approach in #5 and it seems a bit unwieldy.

Here is a snippet from the example output in #5
```json
  "assets": {
    "grib": {
      "href": "https://noaahrrr.blob.core.windows.net/hrrr/hrrr.20240510/conus/hrrr.t12z.wrfsfcf00.grib2",
      "type": "application/wmo-GRIB2",
      "title": "2D Surface Levels",
      "description": "2D Surface Level forecast data as a grib2 file. Subsets of the data can be loaded using the provided byte range.",
      "roles": [
        "data"
      ]
    },
    "index": {
      "href": "https://noaahrrr.blob.core.windows.net/hrrr/hrrr.20240510/conus/hrrr.t12z.wrfsfcf00.grib2.idx",
      "type": "application/x-ndjson",
      "title": "Index file",
      "description": "The index file contains information on each message within the GRIB2 file.",
      "roles": [
        "index"
      ]
    },
    "REFC__entire_atmosphere__analysis": {
      "href": "/vsisubfile/0_238534,/vsicurl/https://noaahrrr.blob.core.windows.net/hrrr/hrrr.20240510/conus/hrrr.t12z.wrfsfcf00.grib2",
      "type": "application/wmo-GRIB2",
      "title": "REFC - entire atmosphere - analysis",
      "hrrr:forecast_layer_type": "analysis",
      "roles": [
        "data"
      ]
    },
    "RETOP__cloud_top__analysis": {
      "href": "/vsisubfile/238534_138642,/vsicurl/https://noaahrrr.blob.core.windows.net/hrrr/hrrr.20240510/conus/hrrr.t12z.wrfsfcf00.grib2",
      "type": "application/wmo-GRIB2",
      "title": "RETOP - cloud top - analysis",
      "hrrr:forecast_layer_type": "analysis",
      "roles": [
        "data"
      ]
    }
  }
}

```

I like how a user could take the `href` and immediately read the data without **any** application code, but it does seem a little unwieldy. I like your idea for an asset-level extension property that holds all of the subset info.

**Comment by hrodmn** [comment]
Here is an example of @TomAugspurger's asset-level properties idea:

https://github.com/developmentseed/noaa-hrrr/blob/01a335d258b40a2aa9cb2dc073cdb5d7bc3c3e75/examples/hrrr-conus-sfc-2024-05-10T12-FH2/hrrr-conus-sfc-2024-05-10T12-FH2.json#L59-L95

**Comment by TomAugspurger** [comment]
One more high-level question (since I haven't had time to review the PR yet), related to data cubes, STAC items, and chunk manifests / virtual Zarr.

IIUC, by storing the byte range offsets of each message in https://github.com/developmentseed/noaa-hrrr/blob/01a335d258b40a2aa9cb2dc073cdb5d7bc3c3e75/examples/hrrr-conus-sfc-2024-05-10T12-FH2/hrrr-conus-sfc-2024-05-10T12-FH2.json#L59-L95, it should be relatively easy (and fast) to form a datacube from a STAC search. Given

1. A list of STAC items with those offsets
2. Some kind of specification for which subset of messages to load (similar to Herbie's `search` thing)

We should be able to make a datacube by

1. Building a [`ChunkManifest`](https://virtualizarr.readthedocs.io/en/latest/generated/virtualizarr.manifests.ChunkManifest.html#virtualizarr.manifests.ChunkManifest) (or is it a `ChunkKey`? and maybe multiple of these, if you're going to combine multiple data variables from the same asset?) for each item
2. Concatenating these into a [`ChunkManifestArray`](https://virtualizarr.readthedocs.io/en/latest/generated/virtualizarr.manifests.ManifestArray.html#virtualizarr.manifests.ManifestArray) through time

This seems pretty useful. It costs extra time when creating the STAC metadata (to extract the offsets) and extra space for storage and transmission of the STAC items. Do folks think the benefit is worth it?

Assuming that's a good idea, I'm struggling a bit with how to expose these datacubes through STAC. Some options I see:

1. I think Henry or Aimee suggested putting the possible "datacube specifications" somewhere on the STAC collection, which seems like a good idea to me. Then (in pseudo-code) this could be

```python
client = pystac_client.Client.open(...)
collection= client.get_collection("noaa-hrr")
items = client.search(collections=collection.id, datetime=[start, end])
search = collection.datacubes["ASNOW:surface:0-45 acc fcst:"]  # get the search string

datasets = [ChunkThing.from_asset(item.assets["data"], search=search) for item in items]
ds = xr.concat(datasets)
```

We could work on higher-level wrappers, but the idea is that the STAC metadata has all the information needed to combine Items into a datacube.

2. How does this relate to storing these chunk manifests in a compressed format like parquet? Perhaps the STAC collection could contain a dictionary of "datacube names" linking to Parquet datasets with the same manifest data?

Sorry to the ramble-y post. Still working through this.

**Comment by hrodmn** [comment]
@TomAugspurger thanks for your thoughts.

> We could work on higher-level wrappers, but the idea is that the STAC metadata has all the information needed to combine Items into a datacube.

Your vision for an application that can use the collection-level datacube schema and the sub-asset metadata to quickly construct an xarray is exactly what I think we want to be able to build.

> This seems pretty useful. It costs extra time when creating the STAC metadata (to extract the offsets) and extra space for storage and transmission of the STAC items. Do folks think the benefit is worth it?

In this case, I am not very concerned about the overhead for STAC metadata generation and storage because we are not dealing with that many items. For any forecast hour there are just two items (conus + alaska). For a whole day's worth of forecasts there are 848 items.

After a lot of trial and error over the last few weeks, here is an outline of an approach that I think we should take for v0.1:

## Collection(s)
* One collection per product
  * The products are different enough that this makes sense. This also aligns with how NOAA segments the data in the documentation.
  * Keep data from FH00-01 and FH02-48 in the same collection. We could separate them since the use-cases for the data in each of the forecast hour sets are different (FH00-01: retrospective analysis of actual conditions, FH02-48: forecasts from current conditions).
 * Add datacube extension to the collection to provide high-level visibility of the dimensions, coordinates, and variables available within a collection.
   * For this to actually make sense, we might need to translate some of the coordinate values from the GRIB files into values that make sense in a datacube context.
   * I am thinking specifically of `forecast_valid` coordinate values like `'2 hour fcst'` or `'0-1 day fcst'` which contain information relative to the `cycle_run_hour` that is already captured in the item datetime property. I propose that we define some key/value pairs like `'forecast_layer_type': 'cumulative_summary'` and `'forecast_statistic': 'maximum'` and `'timedelta_start_minutes': 0`, `'timedelta_end_minutes': 1440` to describe for a `forecast_valid` value like `'0-1 day forecast'`.
   * I don't love the idea of modifying the metadata in a substantial way, so maybe this is a bad idea, but it would facilitate more useful datacubes. I think this is basically what `cfgrib` does to create the list of coherent `xarray.Datasets`.

## Items
* One item per region x cycle run hour x forecast hour
  * to get the most recent forecast for a given hour, filter down to items where `item.datetime == forecast_time`, then sort in descending order by `forecast:reference_time`.
  * to get a retrospective look at actual conditions, filter down to items where `item.properties["forecast:horizon"] == "PT0H"`
* Two assets per item: `grib` and `idx`

## `grib:layers` extension to the `grib` assets
* When I tried this out originally I set it up with a key format of `{variable}__{level}__{forecast_layer_type}`
  ```json
        "grib:layers": {
          "REFC__entire_atmosphere__point_in_time": {
            "description": "Composite reflectivity",
            "unit": "dB",
            "grib_message": 1,
            "start_byte": 0,
            "byte_size": 345203,
            "variable": "REFC",
            "level": "entire atmosphere",
            "forecast_valid": "2 hour fcst",
            "forecast_layer_type": "point_in_time",
            "end_timedelta": 7200.0
          },
          "RETOP__cloud_top__point_in_time": {
            "description": "Echo Top",
            "unit": "m",
            "grib_message": 2,
            "start_byte": 345203,
            "byte_size": 103748,
            "variable": "RETOP",
            "level": "cloud top",
            "forecast_valid": "2 hour fcst",
            "forecast_layer_type": "point_in_time",
            "end_timedelta": 7200.0
          }
      }
  ```

* I could also see how it would be useful to nest the dimensions somehow rather than encoding everything into a single key.
* It is very easy to construct the `dsn` for the specific byte range into a single string that GDAL can use:
  ```python
  def format_vsi_path(grib_asset: Asset, grib_layer_key: str):
      # yank the layer metadata from grib:layers
      layer = grib_asset.extra_fields["grib:layers"][grib_layer_key]
      
      # format the virtual file path for the byte range for this variable
      return f"/vsisubfile/{layer['start_byte']}_{layer['byte_size']},/vsicurl/{grib_asset.href}"
  ```
* Maybe we can try this out for HRRR then upstream it to a proper STAC extension

## Questions
* Put CONUS and Alaska in the same collection or different collections?
* Put forecast hour sets (e.g. FH00-01 / FH02-48) in separate collections?
* Punt on `forecast_valid` value refactoring (`forecast_layer_type`, `forecast_statistic`, `timedelta_start_minutes`, etc) until later?
* The `subh` product has GRIB files with a time dimension in its layers. We could split those out into separate `Items`

**Comment by TomAugspurger** [comment]
> Put CONUS and Alaska in the same collection or different collections?

I could go either way, but lean towards the same collection (assuming the only difference between the two is the AOI covered. If there are differences in the "schema" then Alaska can go on its own)

> Put forecast hour sets (e.g. FH00-01 / FH02-48) in separate collections?

I'm not sure, but I lean towards the same collection? I see your comment about the different use-cases, which is compelling. Can those two use cases be supported by including some condition on the forecast hour set in the query that gets the list of STAC items?

> Punt on forecast_valid value refactoring

I don't have strong thoughts. Seems fine to defer this.

> The subh product has GRIB files with a time dimension in its layers. We could split those out into separate Items

Happy to split out "problematic" items into their own collections if needed. But just to confirm: is this `subh` product in the same GRIB2 file as the other productions? If so, it will feel a bit strange to have the same asset cataloged by multiple STAC items... What effect does the presence of this `subh` product have on the STAC metadata?

**Comment by hrodmn** [comment]
> > Put CONUS and Alaska in the same collection or different collections?
> 
> I could go either way, but lean towards the same collection (assuming the only difference between the two is the AOI covered. If there are differences in the "schema" then Alaska can go on its own)

The only substantial difference between Alaska and CONUS is that Alaska only gets a fresh model run every three hours while CONUS gets a fresh model run every hour. In addition to the non-overlapping spatial extents for the two regions, I added an item-level property `noaa-hrrr:region` which makes it possible to do a simple filter at STAC query time.
 
> > Put forecast hour sets (e.g. FH00-01 / FH02-48) in separate collections?
> 
> I'm not sure, but I lean towards the same collection? I see your comment about the different use-cases, which is compelling. Can those two use cases be supported by including some condition on the forecast hour set in the query that gets the list of STAC items?

The item-level property `forecast:horizon` can be used to apply this filter and we could easily add a `noaa-hrrr:forecast_hour_set` property with values `["FH00-01", "FH02-48"]`. My instinct is to keep them in the same collection and let the user apply whatever filter they want since, in addition to the two use-cases I outlined above, there are probably use-cases where you would want to readily combine data across forecast hour sets.
 
> > The subh product has GRIB files with a time dimension in its layers. We could split those out into separate Items
> 
> Happy to split out "problematic" items into their own collections if needed. But just to confirm: is this `subh` product in the same GRIB2 file as the other productions? If so, it will feel a bit strange to have the same asset cataloged by multiple STAC items... What effect does the presence of this `subh` product have on the STAC metadata?

The way I have it set up right now, every product is in a separate collection. The reason I would consider splitting the `subh` GRIB layers across multiple items is to facilitate loading higher-resolution time series datasets. Without this modification, users and applications will have to do some work to parse the GRIB metadata further and split the 15-minute interval layers into the time dimension.

**Comment by hrodmn** [comment]
re:CONUS / Alaska discussion:
I don't know how we would specify the datacube metadata if we put Alaska and CONUS in the same collection since they use different projections. Specifically, I don't know how we would specify the `x` and `y` dimensions since the coordinate values can't be combined without transforming them to some common CRS.

If the datacube extension metadata is a priority, we will probably need to store CONUS and Alaska in separate collections.

**Comment by abarciauskas-bgse** [comment]
I'm not the STAC expert here but it seems like having a distinct spatial extents and different projections is good enough reason to put Alaska and CONUS into separate collections.

Cool to learn about the vrt:// syntax!

**Comment by hrodmn** [comment]
Thanks all for your feedback and guidance on the best structure - I think we landed on a workable structure.

**Comment by TomAugspurger** [comment]
Nice work!
